sonata_admin:
    title: 'MANUAL.co'
    title_logo: bundles/sonataadmin/images/manual.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
