# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Entity/'
            - '../src/App/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Manual\:
        resource: '../src/Manual'
        exclude:
            - '../src/Manual/Entity/'

    admin.questionnaire:
        class: App\Admin\QuestionnaireAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\Questionnaire, manager_type: orm, label: Questionnaire }
    admin.question:
        class: App\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\Question, manager_type: orm, label: Question}
    admin.option:
        class: App\Admin\OptionAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\Option, manager_type: orm, label: Option}
    admin.option_question:
        class: App\Admin\OptionQuestionAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\OptionQuestion, manager_type: orm, show_in_dashboard: false }
    admin.product_category:
        class: App\Admin\ProductCategoryAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\ProductCategory, manager_type: orm, label: ProductCategory}
    admin.product:
        class: App\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\Product, manager_type: orm, label: Product}
    admin.option_excluded_product:
        class: App\Admin\OptionExcludedProductAdmin
        tags:
            - { name: sonata.admin, model_class: Manual\Entity\OptionExcludedProduct, manager_type: orm, show_in_dashboard: false}
